lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
log_every: 10
eval_every_n_steps: 25
hidden_dim: 256
n_layers: 2
wandb_project: "masked-prosody-modeling-eval"
wandb_mode: "online"
type: "conformer"
dropout: 0.2