lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 512
n_layers: 2
wandb_project: "masked-prosody-modeling-eval"
wandb_mode: "offline"
type: "linear"
use_cwt: True
cwt_n_bins: 34
overwrite_data: False