# lr: 1.0e-3
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 256
n_layers: 2
wandb_project: "masked-prosody-modeling-eval"
wandb_mode: "offline"
type: "linear"
overwrite_data: False