lr: 1.0e-3
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 512
n_layers: 2
wandb_project: "masked-prosody-modeling"
wandb_mode: "online"
timit_phon_focal_loss_alpha: 0.65
timit_word_focal_loss_alpha: 0.87
type: "linear"
overwrite_data: True