lr: 5.0e-5
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 512
n_layers: 2
wandb_project: "masked-prosody-modeling-v2-eval"
wandb_mode: "online"
type: "conformer"
use_mpm: True
mpm_layer: 5
dropout: 0.5