lr: 1.0e-3
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 512
n_layers: 2
wandb_project: "masked-prosody-modeling-v2-eval"
wandb_mode: "offline"
type: "linear"
use_mpm: True
mpm_layer: 7