lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 1000
hidden_dim: 256
n_layers: 2
wandb_project: "masked-prosody-modeling-v2-eval"
wandb_mode: "offline"
type: "conformer"
use_mpm: True
mpm_layer: 7
dropout: 0.2
